refactor(common) migrate from javacript to typescript
shirmagen/HM pull request #13
Opened 2021-08-22 14:13 UTC by OmerDital

2021-08-23 13:21 UTC, benben12341 requested changes

2021-08-23 13:21 UTC, benben12341 commented on client/App/components/Tabs/FirstTab/index.tsx
> +  const calculate = (event: KeyboardEvent) => {
destructure key from event

2021-08-23 13:21 UTC, benben12341 commented on client/App/utilities/axios/generate-api.ts
> +  const put = async (url: string, body: any) => {
destructure > separate parameters

2021-08-23 13:21 UTC, benben12341 commented on client/App/Exterior/Login/LoginForm/Form.tsx
> +type Props = {
I would rename the 'Props' to the name of the components as prefix. e.g 'LoginFormProps'

2021-08-23 13:21 UTC, benben12341 commented on client/App/Exterior/Login/LoginForm/Form.tsx
> +  );
new line at end of file ( git lab get annoyed)

2021-08-23 13:21 UTC, benben12341 commented on client/App/Providers/AlertProvider/index.tsx
> +  const open = (message: string, severity: Color) => {
destructure > separate parameters

2021-08-23 13:21 UTC, benben12341 commented on client/routes.tsx
> +            <ResolvedRoute key={route.name} authRequired={false} {...route} />
authRequried exist in route , its not always false

2021-08-26 06:33 UTC, OmerDital commented on client/App/Providers/AlertProvider/index.tsx
> +  const open = (message: string, severity: Color) => {
Didn't undrstand

2021-08-26 06:37 UTC, OmerDital commented on client/routes.tsx
> +            <ResolvedRoute key={route.name} authRequired={false} {...route} />
does it belong to 'shellRoutes' or to 'exteriorRoutes'?

2021-08-26 06:38 UTC, OmerDital commented on client/App/utilities/axios/generate-api.ts
> +  const put = async (url: string, body: any) => {
destructure is not needed here

2021-08-29 13:31 UTC, merged